# SPI for trackball
CONFIG_SPI=y
CONFIG_INPUT=y

# Pointing device support  
CONFIG_ZMK_POINTING=y

# External power (for trackball)
CONFIG_ZMK_EXT_POWER=y

# Report rate limiter for BLE
CONFIG_ZMK_INPUT_PROCESSOR_REPORT_RATE_LIMIT=y
