manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: billyjacoby
      url-base: https://github.com/billyjacoby
    - name: petejohanson
      url-base: https://github.com/petejohanson/
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: geeksville
      url-base: https://github.com/geeksville
  projects:
    - name: zmk
      remote: billyjacoby
      revision: toucan-kscan-suppression
      import: app/west.yml
    - name: cirque-input-module
      remote: billyjacoby
      revision: toucan-circular-scroll
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: v0.3
  self:
    path: config
