manifest:
  remotes:
    - name: billyjacoby
      url-base: https://github.com/billyjacoby
  projects:
    - name: zmk
      remote: billyjacoby
      revision: main
      import: app/west.yml
  self:
    path: config
